ports:
  - name: Zot registry
    description: Test OCI registry
    port: 5000
    # Do not notify once the port is detected
    onOpen: ignore
    visibility: public
tasks:
  - name: Install Tools
    command: |
      brew tap anchore/grype
      brew install grype trivy
  - name: Display Help
    command: |
      gp open README.md
      brew tap bomctl/bomctl && brew install bomctl

      bomctl