---
name: markdownlint

on:
  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@a23dae216ce3fee4db69da41fed90d2a4af801cf # v19.0.0
        with:
          config: .markdownlint.yml
          globs: "**/*.md"
