---
name: markdownlint

on:
  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@a23dae216ce3fee4db69da41fed90d2a4af801cf # v19.0.0
        with:
          config: .markdownlint.yml
          globs: "**/*.md"
